### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by xixiranran** [TkYu/PowerShellScripts#1]
你好，
1.请问可以做一个脚本可以直接双击使用吗？或者以后用C#做一个图形界面出来。
2.下载的是64位的最新正式版好像，所以建议让用户选择，选择后下载相应的版本，比如正式版，beta版,nightly版等版本。最好把这些命令集成到图形界面就更好了，就好像你的GCsharp一样。
谢谢。

**Comment by TkYu** [comment]
其实这个玩意自己本身就是个脚本，你要是愿意可以自己下载下来运行。

脚本的意义在于简化首次下载的操作而不是自动更新，因为FF的下载地址在国内是没有被墙的，它会在使用过程中自更新，并且会适时提醒重启应用更新，所以就不再需要“更新器”了。

因此，我认为专门写个桌面程序来做这个“下载”操作意义并不大，而一句Power Shell脚本相比之下来得更随性一点，直接在任意一个空目录运行即可。

如果需要稍微定义一点自己的参数，就在运行这句代码之前，运行下面这些语句来设置一下环境变量：

```
- $env:ffdir='D:\firefox' #指定安装的目录，不指定将会默认当前文件夹，如果不存在将会尝试创建
- $env:ffloc='zh-CN' #指定安装语言，如果不指定默认为当前系统语言
- $env:ffarch='win64' #指定下载的架构版本，默认和系统一致，win64代表64位，win代表32位
- $env:ffbranch='beta' #指定下载的分支，默认是正常版，可以填beta、dev、nightly或者esr
```

> PS：cmd中可以通过&&来并列运行语句，例如 SET "ffbranch=beta" && @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/TkYu/PowerShellScripts/master/FirefoxDownload/Firefox.ps1'))"

至于Shuax的Firedoge，运行FirefoxWithFiredoge.ps1即可自动检查并更新

**Comment by xixiranran** [comment]
@TkYu 恩。其实Myfirefox也有这个选择下载什么版本的功能，我觉得不错。你这个工具很好用，只是太全自动了，某些步骤让用户选择来操作就更好了，虽然可以手动设置环境变量。
